### ISSUE TITLE
why is the codes of grounding_trans and rendering_trans in github not the same as that  mentioned in ariticle? 

### ISSUE THREAD

**Issue by 1849615215** [ZHANGDONG-NJUST/FPT#19]
您好，在阅读您的论文和代码时我发现grounding_trans.py 和 rendering_trans.py中的代码和论文中所提的技术细节并不相同，我想向您咨询一下相关的原因。

**Comment by ZHANGDONG-NJUST** [comment]
@1849615215    What exactly are you referring to?

**Comment by 1849615215** [comment]
firstly, I can't find the codes of LGT；then, I don't find the usage of MOS in grounding_trans.py and rendering_trans.py.

**Comment by ZHANGDONG-NJUST** [comment]
@1849615215   1. LGT can be approximated by setting pooling as true; 2. Because MOS itself will bring a great increase in calculations, we only provide this part in ST under some suggestions. If you want to use MOS in other modules, you can follow the same as in ST Parameters to make it work. Thank you~

**Comment by gzbird** [comment]
> @1849615215 1. LGT can be approximated by setting pooling as true; 2. Because MOS itself will bring a great increase in calculations, we only provide this part in ST under some suggestions. If you want to use MOS in other modules, you can follow the same as in ST Parameters to make it work. Thank you~

Could you please provide more details about the LGT and how it can be approximated by setting pooling as true? Thank you.
