### ISSUE TITLE
About FPT for semantic segmentation?

### ISSUE THREAD

**Issue by wy3406** [ZHANGDONG-NJUST/FPT#7]
Hi,Thanks for your work.

Your experiment looks great on Instance-Level Recognition,but it looks strange in Pixel-Level Recognition.You use OCNet+PPM/ASPP/UFP to compare with FPT,but OCNet+PPM/ASPP/UFP reduces the performance of the original OCNet, which looks strange.In addition, the mIoU of PPM, ASPP and UFP is not listed in the paper.Show the training results from the paper [Object-Contextual Representations for Semantic Segmentation]，ASPP is 81.0, PPM is 80.3. Does this mean that FPT cannot use any Head Network？

Can you provide the code for Semantic Segmentation?

Thanks,

**Comment by ZHANGDONG-NJUST** [comment]
Thanks for your attention.  
1.  Results reported in OCNet (81.7% mIoU) is that the model is trained with both the training and val datasets.
2.  Results on PPM/ASPP/UFP+OC are only based on the training dataset.
3.  You mentioned OCRNet is different from OCNet [38].

**Comment by wy3406** [comment]
Thanks for your reply.

1. Results reported in OCNet (80.1% mIoU) is that the model is trained with the training datasets.So OCNet+PPM/ASPP reduces the performance of the original OCNet.My doubt is does this mean that FPT cannot use any Head Network?
2.Can you provide the code for Semantic Segmentation?

Thanks,

**Comment by ZHANGDONG-NJUST** [comment]
Thanks. I do not think we can get the conclusion that "PPM/ASPP+OC reduces the performance of the original OCNet" because the training settings are slightly different. Codes for semantic segmentation may be released in the updated version. FPT is a feature interaction method based on the feature pyramid, so it needs to be based on a specific feature pyramid model, such as PPM, ASPP, or our proposed UFP.  I am not sure what you mean by "Head Network", could you please give some examples to illustrate this ?

**Comment by wy3406** [comment]
Thanks for your reply.
I understand what you mean.
Sorry, I think from the paper Fig.2 that Head Network represents a specific feature pyramid model.

**Comment by ZHANGDONG-NJUST** [comment]
Thank you again for your attention. I will close this question.
